
TYPE
	VIStep_Enum : 
		(
		VISTEP_WAIT,
		VISTEP_GEN_CROSSHAIR,
		VISTEP_CREATE_DIR,
		VISTEP_DELETE_DIR,
		VISTEP_READ_DIR1,
		VISTEP_READ_DIR2,
		VISTEP_READ_DIR3,
		VISTEP_DELETE_IMAGE,
		VISTEP_REQUEST,
		VISTEP_SAVE1,
		VISTEP_SAVE2,
		VISTEP_SAVE3,
		VISTEP_SVG_PREPARE,
		VISTEP_SVG_BAS64_1,
		VISTEP_SVG_BAS64_2,
		VISTEP_SVG_CROSSH,
		VISTEP_SVG_CONCAT,
		VISTEP_SVG_SAVE1,
		VISTEP_SVG_SAVE2,
		VISTEP_SVG_SAVE3,
		VISTEP_ERR
		);
	SvgTexts_Type : 	STRUCT 
		Header1 : STRING[500];
		Header2 : STRING[500];
		Header3 : STRING[500];
		Header4 : STRING[500];
		CrosshairDefinition : STRING[1000];
		Crosshair1 : STRING[500];
		SvgClose : STRING[50];
	END_STRUCT;
	DiagTime_Type : 	STRUCT 
		Refresh : TIME;
		BeginSaveBMPJPG : TIME;
		EndSaveBMPJPG : TIME;
		BeginSVG : TIME;
		BeginSVGSave : TIME;
		EndSVGSave : TIME;
	END_STRUCT;
END_TYPE
