
TYPE
	MTDataCapabilityInternalType : 	STRUCT  (*Internal variables of function block MTDataStdDeviation.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		LowerLimit : LREAL; (*Data for internal use.*)
		UpperLimit : LREAL; (*Data for internal use.*)
		Mean : {REDUND_UNREPLICABLE} LREAL; (*Data for internal use.*)
		Mean2 : {REDUND_UNREPLICABLE} LREAL; (*Data for internal use.*)
		StdDeviation : {REDUND_UNREPLICABLE} LREAL; (*Data for internal use.*)
		Tolerance : {REDUND_UNREPLICABLE} LREAL; (*Data for internal use.*)
		CpkLower : {REDUND_UNREPLICABLE} LREAL; (*Data for internal use.*)
		CpkUpper : {REDUND_UNREPLICABLE} LREAL; (*Data for internal use.*)
		NumberOfValues : UDINT; (*Number of values for output calculation.*)
		InhibitUpdate : BOOL; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Hold : BOOL; (*As long as Hold = TRUE, the output is holding the actual value.*)
	END_STRUCT;
	MTDataStdDeviationInternalType : 	STRUCT  (*Internal variables of function block MTDataStdDeviation.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		Mean : LREAL; (*Sum of input values.*)
		Mean2 : LREAL; (*Sum of the square of the input values.*)
		NumberOfValues : UDINT; (*Number of values for output calculation.*)
		EnableOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Hold : BOOL; (*As long as Hold = TRUE, the output is holding the actual value.*)
	END_STRUCT;
	MTDataVarianceInternalType : 	STRUCT  (*Internal variables of function block MTDataVariance.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		Mean : LREAL; (*Sum of input values.*)
		Mean2 : LREAL; (*Sum of the square of the input values.*)
		NumberOfValues : UDINT; (*Number of values for output calculation.*)
		EnableOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Hold : BOOL; (*As long as Hold = TRUE, the output is holding the actual value.*)
	END_STRUCT;
	MTDataRMSInternalType : 	STRUCT  (*Internal variables of function block MTDataRMS.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		Mean2 : LREAL; (*Sum of the square of the input values.*)
		NumberOfValues : UDINT; (*Number of values for output calculation.*)
		EnableOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Hold : BOOL; (*As long as Hold = TRUE, the output is holding the actual value.*)
	END_STRUCT;
	MTDataMeanInternalType : 	STRUCT  (*Internal variables of function block MTDataMean.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		Mean : LREAL; (*Sum of input values.*)
		NumberOfValues : UDINT; (*Number of values for output calculation.*)
		EnableOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Hold : BOOL; (*As long as Hold = TRUE, the output is holding the actual value.*)
	END_STRUCT;
	MTDataMinMaxInternalType : 	STRUCT  (*Internal variables of function block MTDataMinMax.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		NumberOfValues : UDINT; (*Number of values for output calculation.*)
		EnableOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Hold : BOOL; (*As long as Hold = TRUE, the output is holding the actual values.*)
	END_STRUCT;
	MTDataStatisticsInternalType : 	STRUCT  (*Internal variables of function block MTDataStatistics.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		Buffer : {REDUND_UNREPLICABLE} UDINT; (*Size of window.*)
		BufferOld : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
		BufferMax : {REDUND_UNREPLICABLE} UDINT; (*Size of memory allocation in number of elements.*)
		BufferCntMax : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
		pBuffer : REFERENCE TO REAL; (*Data for internal use.*)
		InOld : REAL; (*Data for internal use.*)
		NumberOfValues : {REDUND_UNREPLICABLE} UDINT; (*Number of values for output calculation.*)
		Number0 : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
    NumberMax : {REDUND_UNREPLICABLE} UDINT; (*Number of saved elements.*)
    IndexMinValue : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
    IndexMaxValue : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
    MinValue : {REDUND_UNREPLICABLE} REAL; (*Data for internal use.*)
    MaxValue : {REDUND_UNREPLICABLE} REAL; (*Data for internal use.*)
    Mean : LREAL; (*Sum of input values.*)
		Mean2 : LREAL; (*Sum of the square of the input values.*)
		Change : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		EnableOld : {REDUND_UNREPLICABLE} BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		ParametersValid : {REDUND_UNREPLICABLE} BOOL; (*Data for internal use.*)
		FirstTime : {REDUND_UNREPLICABLE} BOOL; (*Data for internal use.*)
	END_STRUCT;
END_TYPE
