// --------------------------------------------------------------------------------------------------------------------
// Use this task to add your own code for recipe managment
// --------------------------------------------------------------------------------------------------------------------
PROGRAM _INIT
	// Sample recipe data, the global array REC_VAR_LIST define what variables belong to a recipe
	MaschineData;
	ProductID := 'Cookies';
	CustomerID := 'B&R';
	Recipe_01;
END_PROGRAM

PROGRAM _CYCLIC
	(* Insert code here *)
	
END_PROGRAM

PROGRAM _EXIT
	(* Insert code here *)
	 
END_PROGRAM

